# Generated by Django 5.2.18 on 2026-10-06 21:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0003_exchange_rate_append_only"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("sellable", "Sellable"),
                            ("damaged", "Damaged"),
                            ("inspection", "Awaiting inspection"),
                            ("in_transit", "In transit"),
                        ],
                        default="sellable",
                        max_length=16,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("layer_seq", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CostLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("layer_no", models.PositiveIntegerField()),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantity_initial",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "quantity_remaining",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="layers",
                        to="inventory.stockbalance",
                    ),
                ),
            ],
            options={
                "ordering": ["balance_id", "layer_no"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("sellable", "Sellable"),
                            ("damaged", "Damaged"),
                            ("inspection", "Awaiting inspection"),
                            ("in_transit", "In transit"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening stock"),
                            ("receipt", "Purchase receipt"),
                            ("adjustment_in", "Adjustment (increase)"),
                            ("adjustment_out", "Adjustment (decrease)"),
                        ],
                        max_length=24,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("document_type", models.CharField(max_length=32)),
                ("document_id", models.UUIDField()),
                ("reason", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.costlayer",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="stockbalance",
            index=models.Index(
                fields=["business", "location", "condition"],
                name="inventory_s_busines_8cbffd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.UniqueConstraint(
                fields=("product", "location", "condition"),
                name="inventory_balance_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="inventory_balance_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="costlayer",
            index=models.Index(
                fields=["balance", "layer_no"], name="inventory_c_balance_4a81a7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="costlayer",
            constraint=models.UniqueConstraint(
                fields=("balance", "layer_no"), name="inventory_layer_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="costlayer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_remaining__gte", 0),
                    ("quantity_remaining__lte", models.F("quantity_initial")),
                ),
                name="inventory_layer_remaining_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="costlayer",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_initial__gt", 0)),
                name="inventory_layer_initial_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="costlayer",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)),
                name="inventory_layer_cost_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["business", "product", "-created_at"],
                name="inventory_s_busines_78acaf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["business", "location", "-created_at"],
                name="inventory_s_busines_b0358b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["document_type", "document_id"],
                name="inventory_s_documen_60ee97_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity", 0), _negated=True),
                name="inventory_movement_nonzero",
            ),
        ),
    ]
