# Generated by Django 5.2.18 on 2026-10-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stockmovement_append_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("opening", "Opening stock"),
                    ("receipt", "Purchase receipt"),
                    ("adjustment_in", "Adjustment (increase)"),
                    ("adjustment_out", "Adjustment (decrease)"),
                    ("sale", "Sale"),
                ],
                max_length=24,
            ),
        ),
    ]
