# Generated by Django 5.2.18 on 2026-10-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_sale_movement_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("opening", "Opening stock"),
                    ("receipt", "Purchase receipt"),
                    ("adjustment_in", "Adjustment (increase)"),
                    ("adjustment_out", "Adjustment (decrease)"),
                    ("sale", "Sale"),
                    ("transfer_out", "Transfer (out)"),
                    ("transfer_in", "Transfer (in)"),
                    ("transfer_loss", "Transfer (missing on arrival)"),
                ],
                max_length=24,
            ),
        ),
    ]
