# Generated by Django 5.2.18 on 2026-10-09 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0005_simplify_sales"),
        ("catalog", "0002_product_return_days"),
        ("inventory", "0005_return_movement_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="costlayer",
            index=models.Index(
                condition=models.Q(("quantity_remaining__gt", 0)),
                fields=["business", "balance"],
                name="inventory_layer_live",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["business", "-created_at"],
                name="inventory_s_busines_f753d1_idx",
            ),
        ),
    ]
