# Generated by Django 5.2.18 on 2026-10-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_report_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("opening", "Opening stock"),
                    ("receipt", "Purchase receipt"),
                    ("adjustment_in", "Adjustment (increase)"),
                    ("adjustment_out", "Adjustment (decrease)"),
                    ("sale", "Sale"),
                    ("transfer_out", "Transfer (out)"),
                    ("transfer_in", "Transfer (in)"),
                    ("transfer_loss", "Transfer (missing on arrival)"),
                    ("return_in", "Customer return"),
                    ("inspection_out", "Inspection decided (out)"),
                    ("inspection_in", "Inspection decided (in)"),
                    ("supplier_return", "Return to supplier"),
                    ("warranty_out", "Warranty replacement (out)"),
                    ("warranty_in", "Warranty defective unit (in)"),
                    ("intake", "Received by scanning"),
                ],
                max_length=24,
            ),
        ),
    ]
