# Generated by Django 5.2.18 on 2026-10-07 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0005_simplify_sales"),
        ("catalog", "0002_product_return_days"),
        ("sales", "0005_returns_append_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarrantyClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("customer_phone", models.CharField(blank=True, max_length=60)),
                ("problem", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=8,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("repair", "Repaired"),
                            ("replacement", "Replaced"),
                            ("refund", "Refunded"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                ("out_of_warranty", models.BooleanField(default=False)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("return_id", models.UUIDField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warranty_claims",
                        to="sales.sale",
                    ),
                ),
                (
                    "sale_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warranty_claims",
                        to="sales.saleline",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="WarrantyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("note", "Note"),
                            ("closed", "Closed"),
                        ],
                        max_length=8,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("repair", "Repaired"),
                            ("replacement", "Replaced"),
                            ("refund", "Refunded"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="warranties.warrantyclaim",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="warrantyclaim",
            index=models.Index(
                fields=["business", "status"], name="warranties__busines_641e9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyclaim",
            index=models.Index(
                fields=["business", "-opened_at"], name="warranties__busines_5ace84_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="warrantyclaim",
            constraint=models.UniqueConstraint(
                fields=("business", "number"), name="warranties_claim_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="warrantyclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="warranties_claim_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="warrantyclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("closed_at__isnull", True),
                        ("outcome__isnull", True),
                        ("status", "open"),
                    ),
                    models.Q(
                        ("closed_at__isnull", False),
                        ("outcome__isnull", False),
                        ("status", "closed"),
                    ),
                    _connector="OR",
                ),
                name="warranties_claim_status_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="warrantyclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("return_id__isnull", True), ("outcome", "refund"), _connector="OR"
                ),
                name="warranties_claim_return_only_refund",
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyevent",
            index=models.Index(
                fields=["claim", "created_at"], name="warranties__claim_i_dc528a_idx"
            ),
        ),
    ]
