# Generated by Django 5.2.18 on 2026-10-07 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0005_simplify_sales"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("full", "Everything at the location"),
                            ("partial", "Chosen products"),
                        ],
                        default="full",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Counting"),
                            ("submitted", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.location",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="StockCountLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "baseline_quantity",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "counted_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stockops.stockcount",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dispatched", "In transit"),
                            ("received", "Received"),
                            ("partially_received", "Received, some missing"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="dispatched",
                        max_length=24,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("discrepancy_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.location",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="TransferLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "received_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stockops.transfer",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="stockcount",
            index=models.Index(
                fields=["business", "status"], name="stockops_st_busines_df1494_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcount",
            constraint=models.UniqueConstraint(
                fields=("business", "number"), name="stockops_count_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.UniqueConstraint(
                fields=("count", "product"), name="stockops_cline_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("counted_quantity__isnull", True),
                    ("counted_quantity__gte", 0),
                    _connector="OR",
                ),
                name="stockops_cline_counted_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["business", "status"], name="stockops_tr_busines_a9d244_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.UniqueConstraint(
                fields=("business", "number"), name="stockops_transfer_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_location", models.F("to_location")), _negated=True
                ),
                name="stockops_transfer_two_places",
            ),
        ),
        migrations.AddConstraint(
            model_name="transferline",
            constraint=models.UniqueConstraint(
                fields=("transfer", "product"), name="stockops_tline_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="transferline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="stockops_tline_quantity_positive",
            ),
        ),
    ]
