# Generated by Django 5.2.18 on 2026-10-10 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0005_simplify_sales"),
        ("catalog", "0002_product_return_days"),
        ("stockops", "0001_stock_operations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockIntake",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="StockIntakeLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("cost_known", models.BooleanField(default=False)),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="stockops.stockintake",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddIndex(
            model_name="stockintake",
            index=models.Index(
                fields=["business", "-created_at"],
                name="stockops_st_busines_53d6f6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockintake",
            constraint=models.UniqueConstraint(
                fields=("business", "number"), name="stockops_intake_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockintakeline",
            constraint=models.UniqueConstraint(
                fields=("intake", "product"), name="stockops_iline_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockintakeline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="stockops_iline_quantity_positive",
            ),
        ),
    ]
