# Generated by Django 5.2.18 on 2026-10-09 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_audit_append_only"),
        ("businesses", "0005_simplify_sales"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["business", "action", "-created_at"],
                name="audit_audit_busines_1c4d4a_idx",
            ),
        ),
    ]
