# Generated by Django 5.2.18 on 2026-10-07 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0005_simplify_sales"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="return_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(3650)],
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("return_days__isnull", True),
                    ("return_days__lte", 3650),
                    _connector="OR",
                ),
                name="catalog_product_return_days_max",
            ),
        ),
    ]
