# Generated by Django 5.2.18 on 2026-10-07 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0005_simplify_sales"),
        ("catalog", "0002_product_return_days"),
        ("purchasing", "0002_deliveries_append_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=300)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("credit_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="purchasing.delivery",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.location",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="purchasing.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="SupplierReturnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("condition", models.CharField(max_length=16)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("cost_total", models.DecimalField(decimal_places=5, max_digits=18)),
                (
                    "delivery_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="purchasing.deliveryline",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "supplier_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="purchasing.supplierreturn",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="supplierreturn",
            index=models.Index(
                fields=["business", "-created_at"],
                name="purchasing__busines_f02457_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierreturn",
            constraint=models.UniqueConstraint(
                fields=("business", "number"), name="purchasing_sr_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierreturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="purchasing_sr_line_positive",
            ),
        ),
    ]
