# Generated by Django 5.2.18 on 2026-10-09 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0005_simplify_sales"),
        ("purchasing", "0004_supplier_returns_append_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["business", "-received_at"],
                name="purchasing__busines_c3f240_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["business", "-created_at"],
                name="purchasing__busines_e5bca8_idx",
            ),
        ),
    ]
