# Generated by Django 5.2.18 on 2026-10-07 07:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0004_business_document_details"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=60)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "search_key",
                    models.TextField(blank=True, default="", editable=False),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("customer_phone", models.CharField(blank=True, max_length=60)),
                ("total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "change_given",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "usd_rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="sales.customer",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="SaleLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("unit_symbol", models.CharField(max_length=16)),
                ("unit_decimals", models.PositiveSmallIntegerField()),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("price_currency", models.CharField(max_length=3)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("gross", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("cost_total", models.DecimalField(decimal_places=5, max_digits=18)),
                ("warranty_months", models.PositiveSmallIntegerField(default=0)),
                ("warranty_terms", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="SalePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("transfer", "Bank transfer"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["business", "is_active", "name"],
                name="sales_custo_busines_50b7a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["business", "-created_at"], name="sales_sale_busines_2f6baf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["business", "location", "-created_at"],
                name="sales_sale_busines_273b7d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                fields=("business", "number"), name="sales_sale_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 0)), name="sales_sale_total_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("change_given__gte", 0)),
                name="sales_sale_change_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.UniqueConstraint(
                fields=("sale", "product"), name="sales_line_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="sales_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount__gte", 0), ("discount__lte", models.F("gross"))
                ),
                name="sales_line_discount_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="salepayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="sales_payment_positive"
            ),
        ),
    ]
