# Generated by Django 5.2.18 on 2026-10-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("sales", "0002_sales_append_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salepayment",
            name="sale",
        ),
        migrations.RemoveConstraint(
            model_name="sale",
            name="sales_sale_change_nonneg",
        ),
        migrations.RemoveConstraint(
            model_name="saleline",
            name="sales_line_discount_valid",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="change_given",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="usd_rate",
        ),
        migrations.RemoveField(
            model_name="saleline",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="saleline",
            name="gross",
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("card", "Card")],
                default="cash",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="saleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="sales_line_price_nonneg",
            ),
        ),
        migrations.DeleteModel(
            name="SalePayment",
        ),
    ]
