# Generated by Django 5.2.18 on 2026-10-07 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0005_simplify_sales"),
        ("catalog", "0002_product_return_days"),
        ("sales", "0003_simplify_sales"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="saleline",
            name="return_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=300)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("refund_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("card", "Card")], max_length=16
                    ),
                ),
                ("warranty_claim_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="businesses.location",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="SaleReturnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("unit_symbol", models.CharField(max_length=16)),
                ("unit_decimals", models.PositiveSmallIntegerField()),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("sellable", "Sellable"),
                            ("damaged", "Damaged"),
                            ("inspection", "Awaiting inspection"),
                        ],
                        max_length=16,
                    ),
                ),
                ("refund_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("cost_total", models.DecimalField(decimal_places=5, max_digits=18)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "sale_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="sales.saleline",
                    ),
                ),
                (
                    "sale_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="sales.salereturn",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReturnInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("sellable", "Sellable"), ("damaged", "Damaged")],
                        max_length=16,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections",
                        to="sales.salereturnline",
                    ),
                ),
            ],
            options={
                "ordering": ["decided_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="salereturn",
            index=models.Index(
                fields=["business", "-created_at"],
                name="sales_saler_busines_8ff8e9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.UniqueConstraint(
                fields=("business", "number"), name="sales_return_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("refund_total__gte", 0)),
                name="sales_return_refund_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="sales_return_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(("refund_amount__gte", 0)),
                name="sales_return_line_refund_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="returninspection",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="sales_inspection_quantity_positive",
            ),
        ),
    ]
