# Generated by Django 5.2.18 on 2026-10-06 20:41

import apps.businesses.models
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "currency",
                    models.CharField(
                        choices=[("TMT", "TMT")], default="TMT", max_length=3
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[("ru", "Русский"), ("tk", "Türkmençe")],
                        default="ru",
                        max_length=2,
                    ),
                ),
                (
                    "document_language",
                    models.CharField(
                        choices=[("ru", "Русский"), ("tk", "Türkmençe")],
                        default="ru",
                        max_length=2,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Ashgabat",
                        max_length=64,
                        validators=[apps.businesses.models.validate_timezone],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "businesses",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("store", "Store"), ("warehouse", "Warehouse")],
                        default="store",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("sales", "Sales"),
                            ("warehouse", "Warehouse"),
                        ],
                        max_length=16,
                    ),
                ),
                ("all_locations", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="businesses.business",
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        blank=True, related_name="memberships", to="businesses.location"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                models.F("business"),
                django.db.models.functions.text.Lower("name"),
                name="businesses_location_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "business"), name="businesses_membership_unique"
            ),
        ),
    ]
