# Generated by Django 5.2.18 on 2026-10-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_exchange_rate_append_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="address",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="business",
            name="phone",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="business",
            name="tax_number",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
