# Generated by Django 5.2.18 on 2026-10-07 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0004_business_document_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="tax_number",
        ),
    ]
